name: Documentation

on:
  push:
    branches:
      - main
      - docs-reconcile
    tags: '*'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '**/*.jl'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  docs:
    name: Docs (Julia 1.11)
    permissions:
      contents: write
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-docs-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-docs-artifacts-

      - name: Install dependencies and build docs
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia docs/build.jl

