name: Documentation

on:
  push:
    branches:
      - main
      - docs-reconcile
    tags: '*'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '**/*.jl'

jobs:
  docs:
    name: Docs (Julia 1.11)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-docs-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-docs-artifacts-

      - name: Install documentation dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Install main project dependencies
        run: julia --project=. -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()''

      - name: Build and deploy docs
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl
