name: Documentation

on:
  push:
    branches:
      - docs-reconcile
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Install Conda libnetcdf and set library path
        run: |
          julia --project=docs/ -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
            using Conda;
            Conda.add("libnetcdf");
            println("CONDA_LIB_PATH=", Conda.LIBDIR);
          ' >> $GITHUB_ENV

      - name: Set LD_LIBRARY_PATH and build NCDatasets
        run: |
          export LD_LIBRARY_PATH=${{ env.CONDA_LIB_PATH }}:$LD_LIBRARY_PATH
          julia --project=docs/ -e '
            using Pkg;
            Pkg.build("NCDatasets");
          '

      - name: Debug libnetcdf
        run: |
          find ~/.julia/conda -name "libnetcdf*"
          echo $LD_LIBRARY_PATH

      - name: Build and deploy
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl