name: Testing

on:
  push:
    branches:
      - docs-reconcile # update to match your development branch (master, main, dev, trunk, ...) or '**' for all
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.6', '1.11']
    name: Julia ${{ matrix.julia-version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=test/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run tests
        run: julia --project=test/ test/runtests_structure.jl